services:

  postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itachi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    container_name: auth_mailhog
    ports:
      - "1025:1025"   # SMTP — Spring envoie les emails ici
      - "8025:8025"   # Interface web — tu vois les emails reçus

volumes:
  postgres_data: